"""create beats table

Revision ID: 004c51d80aa5
Revises: b1be963f08e2
Create Date: 2020-06-17 10:03:17.757632

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '004c51d80aa5'
down_revision = 'b1be963f08e2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('beats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('cover_art', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('beats')
    # ### end Alembic commands ###
